### ISSUE TITLE
error parsing my library

### ISSUE THREAD

**Issue by 2600box** [cvzi/itunes_smartplaylist#4]
```
python3 utils/export.py
Reading /Users/apple/Music/iTunes/iTunes Music Library.xml . . .
Traceback (most recent call last):
  File "/Users/apple/dev/itunes_smartplaylist/utils/export.py", line 36, in <module>
    library = itunessmart.readiTunesLibrary(fs)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/itunessmart/library.py", line 57, in readiTunesLibrary
    for event, elem in parser:
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/xml/etree/ElementTree.py", line 1254, in iterator
    yield from pullparser.read_events()
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/xml/etree/ElementTree.py", line 1329, in read_events
    raise event
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/xml/etree/ElementTree.py", line 1301, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 59825, column 11
```

This is line 59825 from the file: 
```
UÆÌD!bŒÖq?˜É`€±</string><string>àm†Ñà±√º
```

Other examples: <string>Blessid Union of Souls    êhÆ</string>

Is it possible to ignore these errors?

Thanks!

**Comment by cvzi** [comment]
You could check if it is an encoding problem. Change line 33 in export.py https://github.com/cvzi/itunes_smartplaylist/blob/45f525562c1c5a3d1124f261ff2924ab612a6853/utils/export.py#L33 to
```python
    with open(iTunesLibraryFile, "r", encoding="utf-8") as fs:
```
